### PR TITLE
Update requirements according to Metanorma format (17-069r3)

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
From https://github.com/metanorma/mn-samples-ogc/issues/64

**Notes:**
- Apparently, cross-references nested in dependencies are not working yet. (I reported the issue here: https://github.com/metanorma/metanorma-standoc/issues/220)

Original:
original-requirement

Code:
````
[[overview]]
=== Overview

[[core]]
[requirement,type="class",label="http://www.opengis.net/spec/ogcapi-features-1/1.0/req/core",obligation="requirement",subject="Web API"]
====
inherit:[<<rfc2616,RFC 2616 (HTTP/1.1)>>]
inherit:[<<rfc2818,RFC 2818 (HTTP over TLS)>>]
inherit:[<<rfc3339,RFC 3339 (Date and Time on the Internet: Timestamps)>>]
inherit:[<<rfc8288,RFC 8288 (Web Linking)>>]
====
````

Generated output:
generated-requirement

Thanks!

### CODE REVIEW

**Comment by ronaldtse** [comment]
Pending action in metanorma/metanorma-standoc#220.

**Comment by ronaldtse** [comment]
@manuel489 : the issue is supposed to be fixed, can you verify? Thanks!

**Comment by manuelfuenmayor** [comment]
> @manuel489 : the issue is supposed to be fixed, can you verify? Thanks!

@ronaldtse , yes, it is fixed now.

*Sample code:*
````
[[overview]]
=== Overview

[[core]]
[requirement,type="class",label="http://www.opengis.net/spec/ogcapi-features-1/1.0/req/core",obligation="requirement",subject="Web API"]
====
inherit:[<<rfc2616,RFC 2616 (HTTP/1.1)>>]
inherit:[<<rfc2818,RFC 2818 (HTTP over TLS)>>]
inherit:[<<rfc3339,RFC 3339 (Date and Time on the Internet: Timestamps)>>]
inherit:[<<rfc8288,RFC 8288 (Web Linking)>>]
====
````

*HTML output:*
requirement-capture


I think you can merge now. And this would close https://github.com/metanorma/mn-samples-ogc/issues/64

Thanks!

**Comment by ronaldtse** [comment]
@manuel489 excellent, thanks!

**Comment by ronaldtse** [comment]
@manuel489 can you add a note in the README.adoc that this document demonstrates Metanorma requirements? Thanks!

**Comment by manuelfuenmayor** [comment]
>@manuel489 can you add a note in the README.adoc that this document demonstrates Metanorma requirements? Thanks!

Ok @ronaldtse , PR added in https://github.com/metanorma/mn-samples-ogc/pull/79

**Pull request merged**
