### PR TITLE
metanorma/metanorma-build-scripts#65 Update GHA configs

### PR DESCRIPTION
**Pull request by CAMOBAP**
As title. 

 _Generated by Cimas_.

### CODE REVIEW

**Comment by ronaldtse** [comment]
The failures here are real

**Comment by CAMOBAP** [comment]
@ronaldtse @opoudjis AFAIR we have a dedicated issue for this https://github.com/metanorma/mn-samples-ogc/issues/119

**Comment by ronaldtse** [comment]
#119 is fixed now but #121 is the new blocker.

**Comment by CAMOBAP** [comment]
Docker passed, merging to allow packed-mn verify the fix

**Pull request merged**
