### PR TITLE
Added 18-016r1 (release-notes doctype)

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
From https://github.com/metanorma/mn-samples-ogc/issues/27

### CODE REVIEW

**Comment by ronaldtse** [comment]
@manuel489 could you have a look at the changes? Some of the anchors didn't link and some code weren't in monospace. Thanks!

**Review by ronaldtse — APPROVED** [review]

**Comment by manuelfuenmayor** [comment]
Hey @ronaldtse , I've checked the commits.
I realize that the changes you did in  "Cleanups to 18-016r1" are related with "18-053r2" doc instead of "18-016r1". (I think that was @anermina 's work.)
Ok, thanks!

**Comment by ronaldtse** [comment]
@manuel489 aha, thanks!

**Comment by anermina** [comment]
Yes, I was working on this document and I'm currently working on solving these issues. Some code wasn't in monospace because I was converting file from HTML, where those parts of the text weren't in monospace. However, I can see they are in DOC/PDF files, so I'm correcting the .adoc.

**Comment by anermina** [comment]
Corrections are added in #47.

**Pull request merged**
