### PR TITLE
OGC 10-100r3: Update 08-scp-sf0.adoc

### PR DESCRIPTION
**Pull request by anermina**
Added some spaces in Table 3 in order to enable generating the last column with code in monospace.

### CODE REVIEW

**Comment by manuelfuenmayor** [comment]
Huh, interesting. Thanks  @anermina for discovering this. I wonder if it should be considered as a bug, what do you think?

**Comment by anermina** [comment]
> Huh, interesting. Thanks @anermina for discovering this. I wonder if it should be considered as a bug, what do you think?

@manuel489 you're right, it might be. I opened a ticket #75 for consultation.

**Comment by ronaldtse** [comment]
Moved issue to metanorma-ogc. Pending outcome of metanorma/metanorma-ogc#122 , once it's fixed we can close this PR without merging.

**Comment by ronaldtse** [comment]
@anermina I believe this bug is fixed and therefore this PR is no longer necessary. Can you help confirm?

**Comment by ronaldtse** [comment]
Confirmed not necessary. Closing.

**Pull request closed without merging**
